ci(embbeded): Keep dist-info directory to have metadata
On some python versions, this directory is needed to correctly load
the duckdb module and its metadata. For example this error happens
with python 3.12.10 but not 3.12.11. One might get the following
error:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\PROGRA~1/QGIS34~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/jfelder/AppData/Roaming/QGIS/QGIS3\profiles\test plugin/python/plugins\qduckdb\provider\duckdb_wrapper.py", line 40, in <module>
    import duckdb
  File "C:\PROGRA~1/QGIS34~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jfelder\AppData\Roaming\QGIS\QGIS3\profiles\test plugin\python\plugins\qduckdb\embedded_external_libs\duckdb\__init__.py", line 163, in <module>
    from duckdb._version import (
  File "C:\PROGRA~1/QGIS34~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jfelder\AppData\Roaming\QGIS\QGIS3\profiles\test plugin\python\plugins\qduckdb\embedded_external_libs\duckdb\_version.py", line 13, in <module>
    __version__: str = _dist_version("duckdb")
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS34~1.7\apps\Python312\Lib\importlib\metadata\__init__.py", line 889, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS34~1.7\apps\Python312\Lib\importlib\metadata\__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS34~1.7\apps\Python312\Lib\importlib\metadata\__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for duckdb